### ISSUE TITLE
请教编译环境问题

### ISSUE THREAD

**Issue by zhihuba** [wonderkun/go-packer#2]
大佬，你好。看了 makefile 文件发现是在linux 下编译的请教下。linux 编译是如何解决 SysWhispers2 #include <Windows.h> 问题的

**Comment by wonderkun** [comment]
linux上编译c语言写的windows程序，是用 mingw。 这里 SysWhispers2 是汇编写的，为了让 mingw能够进行链接，我使用的 uasm编译的 SysWhispers2。
